### ISSUE TITLE
affy package unavailable?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedOvarianData#2]
ExpressionSet class is now provided by the Biobase package instead.

**Comment by lwaldron** [comment]
I think affy is erroring on devel, not deprecated, but in any case I don't think curatedOvarianData has any more use for it, so I should test depending only on Biobase.

**Comment by nick-robo** [comment]
[curatedOvarianData](https://bioconductor.org/packages/release/data/experiment/html/curatedOvarianData.html) is now unavailable in release 3.18.

**Comment by lwaldron** [comment]
Thanks for the report @nick-robo - time for me to fix this.

**Comment by lwaldron** [comment]
This should be fixed in release 3.18 with version 1.40.1 (c16d804) and devel with version 1.41.1 (6a27ac223ff9404d1fa53366b1ceba4db8cfa9bc + 1ef83184773948a02a5f5da214229e281f174f8c) and should appear tomorrow on bioconductor.org if the build system builds it successfully...

**Comment by lwaldron** [comment]
Forgot that experimental data packages only build 3x/wk, still waiting for changes to be built at https://bioconductor.org/packages/curatedOvarianData/

**Comment by lwaldron** [comment]
Resolved and installable now in [release 3.18](https://bioconductor.org/packages/release/data/experiment/html/curatedOvarianData.html) with cOD version 1.40.1 (c16d8042894dbb54e6050b890c6e1c6b8aeac865) and [devel 3.19](https://bioconductor.org/packages/devel/data/experiment/html/curatedOvarianData.html) with version 1.41.1 (6a27ac223ff9404d1fa53366b1ceba4db8cfa9bc + 1ef83184773948a02a5f5da214229e281f174f8c). Thanks for bringing this up.
